vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        publications_images:
            uri_prefix: /publications/images
            upload_destination: '%kernel.project_dir%/public/publications/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
